logging:
  file: logs/log.log
  level.com.dafang.monitor.nx: DEBUG
spring:
  datasource:
    druid:
      url: jdbc:mysql://172.23.106.60:3333/cmdb1.0?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
      username: root
      password: root
      initial-size: 3
      min-idle: 1
      max-active: 50
      test-on-borrow: true
      driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  type-aliases-package: com.dafang.monitor.nx
  mapper-locations: classpath:mapper/*/*.xml
#  type-handlers-package: com.dafang.monitor.nx.*.entity
# 分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql